title: Grupo interinstitucional de herramientas de modelaci贸n para la gesti贸n de la cantidad y calidad de agua  
description: Apoyado por FPTA 358 Fortalecimiento de la Red de Investigaci贸n del INIA en el Manejo Sostenible del Agua para la Producci贸n Agropecuaria y Forestal
show_downloads: false

#baseurl: "/cayman-blog" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "" # change this to the base hostname & protocol for your site


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: 
image: /thumbnail-jumbo.png
twitter:
  username: 

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['novedades','about','grupo','antecedentes','contact']
